################################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

[package]
description = "Zenoh Rust Transport library implementation of the Eclipse uProtocol"
edition = "2021"
include = ["/src/*", "/examples/*", "/Cargo.toml", "/README.md", "/config/*"]
keywords = ["uProtocol", "SDK", "communication", "Zenoh"]
license = "Apache-2.0"
name = "up-transport-zenoh"
readme = "README.md"
repository = "https://github.com/eclipse-uprotocol/up-transport-zenoh-rust"
rust-version = "1.88"
version = "0.10.0-SNAPSHOT"
resolver = "2"

[lints.clippy]
all = "deny"
pedantic = "deny"

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.91"
bytes = "1.12.1"
# addresses https://rustsec.org/advisories/RUSTSEC-2026-0204
crossbeam-epoch = "0.9.20"
# do not use yanked version 0.1.5
keccak = { version = "0.1.6" }
protobuf = { version = "3.7.2" }
# addresses https://rustsec.org/advisories/RUSTSEC-2026-0185.html
quinn-proto = { version = "0.11.15" }
# do not use yanked version 0.9.8
spin = { version = "0.9.9" }
# do not use yanked version 72.1.1
stabby = { version = "72.1.2" }
# addresses https://rustsec.org/advisories/RUSTSEC-2026-0009
time = { version = "0.3.47" }
tokio = { version = "1.53.1", default-features = false }
tracing = "0.1.44"
up-rust = { version = "0.9", default-features = false }
# [impl->dsn~up-transport-zenoh-protocol-version~1]
zenoh = { version = "1.9.0" }

[dev-dependencies]
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive"] }
quinn-proto = { version = "0.11.15" }
serde_json = "1.0.151"
serial_test = { version = "3.5.0" }
test-case = { version = "3.3" }
tokio = { version = "1.53.1", default-features = false, features = ["rt-multi-thread", "signal"] }
tracing-subscriber = "0.3.23"
up-rust = { version = "0.9", features = ["communication", "test-util"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[package.metadata.docs.rs]
all-features = true
