# ********************************************************************************
#  Copyright (c) 2025 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Config file for cargo deny
# For all options see https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

# If you add a license in the following section also consider changing about.toml
[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    # CDLA-Permissive-2.0 is not (yet) on the Eclipse Foundation's list of approved licenses
    "CDLA-Permissive-2.0",
    "EPL-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    # Unicode-3.0 is not (yet) on the Eclipse Foundation's list of approved licenses
    # however, all of its predecessors are, thus we assume that 3.0 is also ok to use
    "Unicode-3.0",
    "Zlib",
]
private = { ignore = true }
unused-allowed-license = "allow"

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
]
skip-tree = [
    { crate = "zenoh@1.9.0", reason = "Zenoh notoriously uses multiple different versions of crates" },
    { crate = "protobuf-codegen@3.7.2", reason = "only used as part of the build process" },
]

[advisories]
ignore = [
    { id = "RUSTSEC-2023-0071", reason = "There currently is no version of the rsa crate available that fixes this vulnerability" },
    { id = "RUSTSEC-2024-0436", reason = "The paste crate is no longer maintained; we accept this risk for the time being, until zenoh has replaced it with something else" },
    { id = "RUSTSEC-2025-0134", reason = "Zenoh needs to remove its dependency on rustl_pemfile; however, based on the RUSTSEC description, there should be no imminent risk involved in the short term" },
    { id = "RUSTSEC-2026-0041", reason = "The lz4_flex crate is used by Zenoh for compressing data that is transmitted via the network. However, this is an optional feature that needs to be enabled explicitly by clients. This transport does not itself enable compression and logs warning messages if a client enables it." },
]
