# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Checks if the crate can be built using the latest stable toolchain with the latest
# compatible dependencies.
# The job definition has been inspired by the example given in the Rust Cargo book.

name: Check latest dependencies

on:
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  latest-deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
    - uses: actions/checkout@v4
    - run: rustup update stable && rustup default stable
    - run: cargo update --verbose
    - run: cargo build --verbose --all-features
    - run: cargo test --verbose --all-features
